apiVersion: v1
kind: Service
metadata:
  name: banking-admin-core
  namespace: banking
  labels:
    name: banking-admin-core
spec:
  ports:
  - name: http
    port: 9010
    targetPort: 9010
  selector:
    app: banking-admin-core

